### ISSUE TITLE
Optional argument in copy! procedures

### ISSUE THREAD

**Issue by Zipheir** [diamond-lizard/srfi-160#1]
The `start` and `end` arguments to `@vector-copy!` and `@vector-reverse-copy!` should be optional, per the SRFI document.

**Comment by diamond-lizard** [comment]
This bug has been submitted upstream.
Waiting for upstream fix.

**Comment by diamond-lizard** [comment]
In #chicken, Zipheir wrote:

"You may want to cherry-pick this commit for your SRFI 160 egg."

and pasted a ilnk to: https://github.com/johnwcowan/srfi-160/commit/8fd5bbc47d053317bd1912269c549ec22bceaba9

"It fixes the optional-arguments bug for @vector-copy!"
