### ISSUE TITLE
Broken variadic case of at_vector=

### ISSUE THREAD

**Issue by Zipheir** [diamond-lizard/srfi-160#5]
This error causes `u8vector=`, etc. to return an unspecified value when called with more than two vectors.

It is fixed in the first commit added this pull request to John Cowan's repo:

https://github.com/johnwcowan/srfi-160/pull/4

EDIT: This issue is holding up the SRFI 178 egg.

**Comment by diamond-lizard** [comment]
Fixed in commits: c4f4a3c and a2267dd

Version [0.3](https://github.com/diamond-lizard/srfi-160/releases/tag/0.3) contains contains these fixes.
